These exercises are inspired from Andrew Ng Coursera Deep Learning specialisation

In [2]:
import numpy as np
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [5]:
b = np.random.rand(1000000)
c = np.random.rand(1000000)

import time
time1 = time.time()
d = np.dot(b, c)
print(d)
time2 = time.time()

print("runtime vectorized = " +str(1000*(time2-time1)) + "ms")

250216.66165521517
runtime vectorized = 94.1622257232666ms


In [6]:
time1 = time.time()

e = 0
for i in range(1000000):
    e += b[i]*c[i]
print(e)
time2 = time.time()
print("runtime non vectorized = " +str(1000*(time2-time1)) + "ms")

250216.6616552205
runtime non vectorized = 458.06312561035156ms


###### Exercise

Turn the following imperative method into a vectorized computation using numpy.

 - apply the exponential operation to each element of a vector u.
 - we will store the outputs in a vector w of same dimensions than u.    

In [7]:
import math
n=3
u = np.random.rand(n)
v = np.zeros((n, 1))

print(v)
print(u)

for i in range(n):
    v[i]= math.exp(u[i])
print(v)

[[0.]
 [0.]
 [0.]]
[0.31367965 0.65347872 0.51731834]
[[1.36845128]
 [1.92221607]
 [1.67752307]]


In [8]:
w = np.exp(u)

do the same on a matrix A of dimension 4 by 3 and store the results in an object z

In [9]:
A = np.random.rand(4,3)
print(A)
print(type(A))

[[0.73719226 0.80271871 0.16881723]
 [0.85206172 0.68747221 0.10669064]
 [0.27288805 0.6848828  0.83753191]
 [0.55983352 0.82192214 0.71091799]]
<class 'numpy.ndarray'>


In [10]:
z = np.exp(A)

In [11]:
z

array([[2.09005892, 2.23159976, 1.18390374],
       [2.34447552, 1.9886822 , 1.11259001],
       [1.31375317, 1.98353935, 2.31065702],
       [1.75038107, 2.27486826, 2.03585929]])

compute Ax + b, assuming x is a vector of same length that A rows and b is a scalar

In [14]:
x = np.random.rand(4,1)
b = 2
A*x + b

array([[2.50060741, 2.54510466, 2.11463924],
       [2.60583177, 2.48880556, 2.07585904],
       [2.11979993, 2.30066875, 2.36768286],
       [2.39555773, 2.5807399 , 2.50230845]])