###### These exercises are inspired from Andrew Ng Coursera Deep Learning specialisation and INRIA FUN MOOC on Python 

Broadcasting in python is a mecanism which duplicates a scalar or vector to perform elementwise operations on matrix or vectors

In [1]:
import numpy as np
A = np.random.rand(4,3)
print(A)

[[0.77416691 0.22408676 0.0510692 ]
 [0.4923907  0.03395842 0.1483155 ]
 [0.05131575 0.58869329 0.31063052]
 [0.12123201 0.89003102 0.14015927]]


For instance, we can broadcast a scalar b to add b to each element of A

In [13]:
b = 2
A + b

array([[[2.74931731, 2.94175123, 2.20411958, 2.75756104, 2.79395681],
        [2.0660369 , 2.01641014, 2.90683938, 2.72585508, 2.64848868],
        [2.44920081, 2.79678855, 2.14363587, 2.45709468, 2.59866389]],

       [[2.83051042, 2.33861961, 2.15276751, 2.12560067, 2.45334099],
        [2.44714551, 2.4979457 , 2.34485592, 2.06131361, 2.10864827],
        [2.7621195 , 2.79506279, 2.19135364, 2.11457318, 2.79037901]],

       [[2.10684181, 2.9100713 , 2.31337414, 2.59593855, 2.84480296],
        [2.61429927, 2.98893651, 2.95151774, 2.62733888, 2.49601939],
        [2.88799189, 2.32895959, 2.01588637, 2.23112043, 2.65652954]],

       [[2.83199305, 2.35121368, 2.88293631, 2.93272714, 2.70249558],
        [2.70236497, 2.59067982, 2.13421244, 2.59988788, 2.92496646],
        [2.49194728, 2.1034216 , 2.12267642, 2.37873676, 2.48765573]],

       [[2.59165303, 2.09347783, 2.20595891, 2.24773111, 2.340295  ],
        [2.71729191, 2.45688907, 2.4548473 , 2.02762855, 2.03133096],
        [2.4

to sum horizontally the elements of A, we can call sum on A with the argument axis = 1

In [2]:
A.sum(axis= 1)

array([1.04932287, 0.67466462, 0.95063956, 1.1514223 ])

to sum vertically, the argument is axis =0

We can do elementwise operations between a matrix with a vector thanks to python broadcasting.
Let's define a vector u as the vertical sum of all columns of A and use it on A

In [3]:
u = A.sum(axis = 0)
print(u)
print(u.shape)

[1.43910538 1.73676948 0.6501745 ]
(3,)


For security reshape u to force its shape (1,3). Defining a vector with only one dimension, leaving the other empty such as u is defined above, can have terrible cost in debugging.

In [4]:
u = u.reshape(1,3)
print(u.shape)

(1, 3)


divide A by u

In [5]:
div = A/u
print(div)

[[0.53795012 0.12902504 0.07854692]
 [0.34215055 0.01955263 0.22811646]
 [0.03565809 0.33895879 0.47776485]
 [0.08424123 0.51246353 0.21557178]]


In [6]:
We have broadcasted vector u on each element of A

SyntaxError: invalid syntax (<ipython-input-6-f6b004d5259a>, line 1)

Exercise:
compute, for each values of A, its percentage in regard of the total column sum of A and store it in a object w

Lets define two matrix with different dimensions, (3, 1) and (1, 5)

In [7]:
col = np.arange(1, 4).reshape((3, 1))
print(col)

[[1]
 [2]
 [3]]


In [8]:
line = 100 * np.arange(1, 6)
print(line)

[100 200 300 400 500]


Add the two matrix col and line thanks to broadcasting

In [9]:
m = col + line
print(m)

[[101 201 301 401 501]
 [102 202 302 402 502]
 [103 203 303 403 503]]


Broacasting base rules  
We can broadcast A and B when there is a dimension C which 'spreads' both these of A and B  
So we can only broadcast from 1 to n.  
If there is a dimension p> 1 dividing n,  we cannot broadcast from p to n.

Define  

A with dimensions  15 x 3 x 5  
B with dimensions  15 x 1 x 5  
verify A+B has dimensions 15 x 3 x 5  

Try also for 

B is dimensions 3 x 5  
B is dimensions 3 x 1  
B is dimensions 1  

In [10]:
A = np.random.rand(15,3,5)
B = np.random.rand(15,1,5)

In [11]:
C = A+B

In [12]:
C.shape

(15, 3, 5)

Define A nd B with following dimensions and check if you can broadcast

A      2 x 1
B  8 x 4 x 3