###### These exercises are inspired from Andrew Ng Coursera Deep Learning specialisation and INRIA MOOC on FUN platform

In [2]:
import numpy as np
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


###### Benchmark a vectorised and an non vectorized version of the dot product

In [5]:
b = np.random.rand(1000000)
c = np.random.rand(1000000)

import time
time1 = time.time()
d = np.dot(b, c)
print(d)
time2 = time.time()

print("runtime vectorized = " +str(1000*(time2-time1)) + "ms")

250216.66165521517
runtime vectorized = 94.1622257232666ms


In [6]:
time1 = time.time()

e = 0
for i in range(1000000):
    e += b[i]*c[i]
print(e)
time2 = time.time()
print("runtime non vectorized = " +str(1000*(time2-time1)) + "ms")

250216.6616552205
runtime non vectorized = 458.06312561035156ms


###### Exercises

Turn the following imperative method into a vectorized computation using numpy.
 
   - apply the exponential operation to each element of a vector u.
   - we will store the outputs in a vector w of same dimensions than u.    


In [7]:
import math
n=3
u = np.random.rand(n)
v = np.zeros((n, 1))

print(v)
print(u)

for i in range(n):
    v[i]= math.exp(u[i])
print(v)

[[0.]
 [0.]
 [0.]]
[0.31367965 0.65347872 0.51731834]
[[1.36845128]
 [1.92221607]
 [1.67752307]]


Do the same on a matrix A of dimension 4 by 3 and store the results in an object z.  
Generate A with the random method of numpy.

[[0.73719226 0.80271871 0.16881723]
 [0.85206172 0.68747221 0.10669064]
 [0.27288805 0.6848828  0.83753191]
 [0.55983352 0.82192214 0.71091799]]
<class 'numpy.ndarray'>


Compute Ax + b, assuming x is a vector of same length that A rows and b is a scalar.  
Generate A and x with the random method of numpy.