<style>div.title-slide {    width: 100%;    display: flex;    flex-direction: row;            /* default value; can be omitted */    flex-wrap: nowrap;              /* default value; can be omitted */    justify-content: space-between;}</style><div class="title-slide">
<span style="float:left;">Licence CC BY-NC-ND</span>
<span>Thierry Parmentelat &amp; Arnaud Legout</span>
<span><img src="media/both-logos-small-alpha.png" style="display:inline" /></span>
</div>

# Index and slicing

In [3]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
plt.ion()

### Indexation with ints and tuples

In [4]:
# this function creates a table
# tab[i, j] = i + 10 * j
def background(n):
    i = np.arange(n)
    j = i.reshape((n, 1))
    return i + 10 * j

In [5]:
a5 = background(5)
print(a5)

[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]
 [40 41 42 43 44]]


With one index we get a line

In [6]:
a5[1]

array([10, 11, 12, 13, 14])

In [7]:
# with 2 indexes
a5[1][2]

12

In [8]:
# or we can index from a tuple
a5[1, 2]

12

In [9]:
# we can affect a cell of an array individually
a5[2][1] = 221
a5[3, 2] += 300
print(a5)

[[  0   1   2   3   4]
 [ 10  11  12  13  14]
 [ 20 221  22  23  24]
 [ 30  31 332  33  34]
 [ 40  41  42  43  44]]


In [10]:
# or a whole line
a5[1] = np.arange(100, 105)
print(a5)

[[  0   1   2   3   4]
 [100 101 102 103 104]
 [ 20 221  22  23  24]
 [ 30  31 332  33  34]
 [ 40  41  42  43  44]]


In [11]:
# as previsously sene we can affect with boradcasting
a5[4] = 400
print(a5)

[[  0   1   2   3   4]
 [100 101 102 103 104]
 [ 20 221  22  23  24]
 [ 30  31 332  33  34]
 [400 400 400 400 400]]


# Slicing

thanks to slicing we can affect by columns

In [12]:
a5 = background(5)
print(a5)

[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]
 [40 41 42 43 44]]


In [13]:
a5[:, 3]

array([ 3, 13, 23, 33, 43])

The output is a one table array, but we can modify the whole column by affecting from range

In [13]:
a5[:, 3] = range(300, 305)
print(a5)

[[  0   1   2 300   4]
 [ 10  11  12 301  14]
 [ 20  21  22 302  24]
 [ 30  31  32 303  34]
 [ 40  41  42 304  44]]


or by broadcast

In [14]:
# we can affect a scalar to a whole column
a5[:, 2] = 200
print(a5)

[[  0   1 200 300   4]
 [ 10  11 200 301  14]
 [ 20  21 200 302  24]
 [ 30  31 200 303  34]
 [ 40  41 200 304  44]]


In [15]:
# or add a scalar to a column
a5[:, 4] += 400
print(a5)

[[  0   1 200 300 404]
 [ 10  11 200 301 414]
 [ 20  21 200 302 424]
 [ 30  31 200 303 434]
 [ 40  41 200 304 444]]


Les slices peuvent prendre une forme générale :

In [16]:
a8 = background(8)
print(a8)

[[ 0  1  2  3  4  5  6  7]
 [10 11 12 13 14 15 16 17]
 [20 21 22 23 24 25 26 27]
 [30 31 32 33 34 35 36 37]
 [40 41 42 43 44 45 46 47]
 [50 51 52 53 54 55 56 57]
 [60 61 62 63 64 65 66 67]
 [70 71 72 73 74 75 76 77]]


In [17]:
# all the lines in rows 1, 4, 7
a8[1::3]

array([[10, 11, 12, 13, 14, 15, 16, 17],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [70, 71, 72, 73, 74, 75, 76, 77]])

In [18]:
# columns 1, 5
a8[:, 1::4]

array([[ 1,  5],
       [11, 15],
       [21, 25],
       [31, 35],
       [41, 45],
       [51, 55],
       [61, 65],
       [71, 75]])

In [19]:
# and we can modify them
a8[:, 1::4] = 0
print(a8)

[[ 0  0  2  3  4  0  6  7]
 [10  0 12 13 14  0 16 17]
 [20  0 22 23 24  0 26 27]
 [30  0 32 33 34  0 36 37]
 [40  0 42 43 44  0 46 47]
 [50  0 52 53 54  0 56 57]
 [60  0 62 63 64  0 66 67]
 [70  0 72 73 74  0 76 77]]


so slicing can help us to extract blocks :

In [21]:
print(a8[5:8, 2:5])

[[52 53 54]
 [62 63 64]
 [72 73 74]]


### `newaxis`

We can use `np.newaxis` with a slice to  shift the dimensions

In [22]:
X = np.arange(1, 7)
print(X)

[1 2 3 4 5 6]


In [23]:
X.shape

(6,)

In [24]:
Y = X[:, np.newaxis]
print(Y)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [25]:
Y.shape

(6, 1)

In [26]:
Z = Y[:, np.newaxis]
Z

array([[[1]],

       [[2]],

       [[3]],

       [[4]],

       [[5]],

       [[6]]])

In [27]:
Z.shape

(6, 1, 1)

Combining slicing to create X et Y, broadcasting to create their sum, we can create the table of all possible outcomes of 2 dices

In [28]:
dice2 = X + Y
print(dice2)

[[ 2  3  4  5  6  7]
 [ 3  4  5  6  7  8]
 [ 4  5  6  7  8  9]
 [ 5  6  7  8  9 10]
 [ 6  7  8  9 10 11]
 [ 7  8  9 10 11 12]]


Or all the outcomes of 6 dices :

In [29]:
dice3 = X + Y + Z
print(dice3)

[[[ 3  4  5  6  7  8]
  [ 4  5  6  7  8  9]
  [ 5  6  7  8  9 10]
  [ 6  7  8  9 10 11]
  [ 7  8  9 10 11 12]
  [ 8  9 10 11 12 13]]

 [[ 4  5  6  7  8  9]
  [ 5  6  7  8  9 10]
  [ 6  7  8  9 10 11]
  [ 7  8  9 10 11 12]
  [ 8  9 10 11 12 13]
  [ 9 10 11 12 13 14]]

 [[ 5  6  7  8  9 10]
  [ 6  7  8  9 10 11]
  [ 7  8  9 10 11 12]
  [ 8  9 10 11 12 13]
  [ 9 10 11 12 13 14]
  [10 11 12 13 14 15]]

 [[ 6  7  8  9 10 11]
  [ 7  8  9 10 11 12]
  [ 8  9 10 11 12 13]
  [ 9 10 11 12 13 14]
  [10 11 12 13 14 15]
  [11 12 13 14 15 16]]

 [[ 7  8  9 10 11 12]
  [ 8  9 10 11 12 13]
  [ 9 10 11 12 13 14]
  [10 11 12 13 14 15]
  [11 12 13 14 15 16]
  [12 13 14 15 16 17]]

 [[ 8  9 10 11 12 13]
  [ 9 10 11 12 13 14]
  [10 11 12 13 14 15]
  [11 12 13 14 15 16]
  [12 13 14 15 16 17]
  [13 14 15 16 17 18]]]


For the record, with `np.unique`, we can compute the number of occurences in the table, so compute all the probablilities of outcomes for numbers between 3 and 18 :

In [30]:
np.unique(dice3, return_counts=True)

(array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18]),
 array([ 1,  3,  6, 10, 15, 21, 25, 27, 27, 25, 21, 15, 10,  6,  3,  1], dtype=int64))

### Differences from lists

Indexing and slicing over np.arrays create views over blocks of an array, they can be twisted and their dimensions can be reaffected.

Differences betweenn `numpy` arrays and lists, regarding indexing and slicing

#### slicing cannot change the size of an array

The size of a  `numpy` object is constant, so its size cannot be changed, on the contrary of lists which can be modified with slicing

##### Lists

In [32]:
# possible
liste = [0, 1, 2]
liste[1:2] = [100, 102, 102]
liste

[0, 100, 102, 102, 2]

##### np.arrays

In [33]:
# not possible
array = np.array([0, 1, 2])
try:
    array[1:2] = np.array([100, 102, 102])
except Exception as e:
    print(f"OOPS, {type(e)}, {e}")

OOPS, <class 'ValueError'>, could not broadcast input array from shape (3) into shape (1)


##### we can modify an array by modifying the slice

A slice on a np object is a view over an extract of the array, changing the view we affect the table. Which is not what happens on lists.

##### Lists

In [33]:
# une slice of a list is a shallow copy
liste = [0, 1, 2]
liste[1:2]

[1]

In [34]:
# so modifying the slice we do not affect the list
liste[1:2][0] = 999999
liste

[0, 100, 102, 102, 2]

##### np.arrays

In [35]:
# a slice of a np.array is an extract of the array
array = np.array([0, 1, 2])
array[1:2]

array([1])

In [36]:
#so modifying the slice we change the arrays
array[1:2][0] = 100
array

array([  0, 100,   2])